### PR TITLE
Added new method match_string

### PR DESCRIPTION
**Pull request by abhimanyusharma003**
Added new method `match_string` it will take two parameters `$pattern` and `$string` and return `true` or `false`.
`$parttern` can be regex or direct string like `Hello`
`$string` it will be string that need to compare or match with regex.

### CODE REVIEW

**Comment by brandonwamboldt** [comment]
Thanks! Keep it up :smile:

**Comment by brandonwamboldt** [comment]
I assume it was meant to be:

```
return (bool) preg_match('#^' . $pattern . '$#', $string);
```

Note the `$`. Other wise we match any string that starts with our term. I will fix it

**Comment by brandonwamboldt** [comment]
I also added a case sensitivity flag to it. See 1ef207acc00d35e40ac1d53a762cdc46398933fd

**Comment by brandonwamboldt** [comment]
And I just saw the `\z`! My bad, disregard my other comment.

**Comment by abhimanyusharma003** [comment]
Case sensitivity is awesome addition :heart:ed it

**Pull request merged**
