### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by brandonwamboldt** [comment]
You've broken `array_get`, I can't merge this

**Comment by lyrixx** [comment]
oups, fixed ;)

**Comment by lyrixx** [comment]
@brandonwamboldt BTW, the implementations of `array_get` is wrong:

```php
<?php
require __DIR__.'/vendor/autoload.php';
$a = ['a' => null];
var_dump(utilphp\util::array_get($a['a'], 'default value'));
```
```bash
>(13)[/tmp/utilphp](master %) php test.php 
string(13) "default value"
```

**Comment by brandonwamboldt** [comment]
Thanks for fixing the PR. I'll investigate the issue with `array_get` to see if its possible to fix.

**Comment by brandonwamboldt** [comment]
Sadly, the internal behavior of PHP when you ask for a reference to a non-existent variable is to create a variable and set it to `NULL`, so there is no way to distinguish between a `NULL` value and a missing value. For the use case I envisioned for `array_get` that should be fine, I'll just add a note to the docs.

**Comment by lyrixx** [comment]
I know. that's why I initially tried to fix it by updating the method signature.
You can find a working implementation [there](https://github.com/igorw/get-in).

**Pull request merged**
