### PR TITLE
random_string function improvement

### PR DESCRIPTION
**Pull request by abhimanyusharma003**
If `$no_duplicate_chars` is `false` then generate random string using internal php functions.

### CODE REVIEW

**Comment by hopeseekr** [comment]
Hey @abhimanyusharma003 . It looks pretty technical. Any chance you can add appropriate unit tests for the new stuff?

**Comment by brandonwamboldt** [comment]
So this revealed both an error in my code and a problem with the test suite, which I've now fixed. That said, your function fails to produce a random string with no duplicated characters when the appropriate options are set.

**Comment by brandonwamboldt** [comment]
I will re-open if you fix the error.

**Comment by abhimanyusharma003** [comment]
@hopeseekr No it's not much technical, just using internal php functions to generate random characters then using a loop. I will give try to improve test from further on. 

@brandonwamboldt I have opened a new pull request, if it looks ok to you :)

**Pull request closed without merging**
