### PR TITLE
Added separator support

### PR DESCRIPTION
**Pull request by abhimanyusharma003**
Added support for separator and few tests. After you have now have ability to generate different type of slugs.

### CODE REVIEW

**Comment by brandonwamboldt** [comment]
Thanks! I'm going to make a slight change to this to allow the old parameter ordering as well, and throw `E_USER_DEPRECATED` to maintain semvar compliance a little.

**Comment by brandonwamboldt** [comment]
Loving the changes, keep them up!

**Comment by brandonwamboldt** [comment]
Also, please take a look at my change: https://github.com/brandonwamboldt/utilphp/commit/445156d9d5d758cda2aff8bc8c8043e9bf8bbdcc

If you're going to change something like parameter ordering and break backwards compatability, try to do it like that next time! People can upset when function signatures randomly change. Thanks :smile:

**Comment by abhimanyusharma003** [comment]
You are very right, I will make sure this thing from the next time. 
We can also tag repo for new release when ever there is a function parameters change, this way it might/will not break older codes ( If they are using proper version in there composer.json file ). :)

**Pull request merged**
